#!/usr/bin/env bash
set -euo pipefail

# Interactive .env generator for vet-bill-fair
# Usage:
#   ./scripts/setup-env.sh            # writes .env
#   ./scripts/setup-env.sh .env.local # writes custom file

OUT_FILE="${1:-.env}"

cd "$(dirname "$0")/.."

prompt() {
  local key="$1"; shift
  local help="$1"; shift || true
  local secret="${1:-false}"

  local val=""
  if [[ "$secret" == "true" ]]; then
    read -r -s -p "$key ($help): " val
    echo
  else
    read -r -p "$key ($help): " val
  fi
  echo "$val"
}

rand_token() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    # fallback
    python3 - <<'PY'
import secrets
print(secrets.token_hex(32))
PY
  fi
}

echo "Writing env to: $OUT_FILE"

DATABASE_URL=$(prompt DATABASE_URL "Railway Postgres URL (can leave blank for now)" false)
APP_URL=$(prompt APP_URL "http://localhost:3000 for local dev" false)

# Turnstile
TURNSTILE_SECRET_KEY=$(prompt TURNSTILE_SECRET_KEY "Cloudflare Turnstile secret key" true)
NEXT_PUBLIC_TURNSTILE_SITE_KEY=$(prompt NEXT_PUBLIC_TURNSTILE_SITE_KEY "Cloudflare Turnstile site key (public)" false)

# R2
R2_ACCOUNT_ID=$(prompt R2_ACCOUNT_ID "Cloudflare account id" false)
R2_ACCESS_KEY_ID=$(prompt R2_ACCESS_KEY_ID "R2 access key id" false)
R2_SECRET_ACCESS_KEY=$(prompt R2_SECRET_ACCESS_KEY "R2 secret access key" true)
R2_BUCKET_NAME=$(prompt R2_BUCKET_NAME "R2 bucket name" false)
R2_ENDPOINT=$(prompt R2_ENDPOINT "https://<accountid>.r2.cloudflarestorage.com (recommended)" false)

# Stripe
STRIPE_SECRET_KEY=$(prompt STRIPE_SECRET_KEY "Stripe secret key" true)
STRIPE_WEBHOOK_SECRET=$(prompt STRIPE_WEBHOOK_SECRET "Stripe webhook secret (whsec_...)" true)
STRIPE_PRICE_ID=$(prompt STRIPE_PRICE_ID "Stripe price id (price_...)" false)

# Admin token
ADMIN_TOKEN_INPUT=$(prompt ADMIN_TOKEN "Leave blank to auto-generate" true)
if [[ -z "${ADMIN_TOKEN_INPUT}" ]]; then
  ADMIN_TOKEN=$(rand_token)
  echo "Generated ADMIN_TOKEN: $ADMIN_TOKEN"
else
  ADMIN_TOKEN="$ADMIN_TOKEN_INPUT"
fi

# App knobs
MAX_UPLOAD_BYTES=$(prompt MAX_UPLOAD_BYTES "Optional (default 10485760)" false)
ALLOWED_MIME_TYPES=$(prompt ALLOWED_MIME_TYPES "Optional (default application/pdf,image/jpeg,image/png)" false)
RATE_LIMIT_PER_MINUTE=$(prompt RATE_LIMIT_PER_MINUTE "Optional (default 10)" false)

# Defaults
: "${APP_URL:=http://localhost:3000}"
: "${MAX_UPLOAD_BYTES:=10485760}"
: "${ALLOWED_MIME_TYPES:=application/pdf,image/jpeg,image/png}"
: "${RATE_LIMIT_PER_MINUTE:=10}"

cat > "$OUT_FILE" <<EOF
# Generated by scripts/setup-env.sh

# Core
DATABASE_URL=${DATABASE_URL}
APP_URL=${APP_URL}

# Admin
ADMIN_TOKEN=${ADMIN_TOKEN}

# Cloudflare Turnstile
TURNSTILE_SECRET_KEY=${TURNSTILE_SECRET_KEY}
NEXT_PUBLIC_TURNSTILE_SITE_KEY=${NEXT_PUBLIC_TURNSTILE_SITE_KEY}

# Cloudflare R2 (S3-compatible)
R2_ACCOUNT_ID=${R2_ACCOUNT_ID}
R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
R2_BUCKET_NAME=${R2_BUCKET_NAME}
R2_ENDPOINT=${R2_ENDPOINT}

# Stripe
STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
STRIPE_PRICE_ID=${STRIPE_PRICE_ID}

# App limits
MAX_UPLOAD_BYTES=${MAX_UPLOAD_BYTES}
ALLOWED_MIME_TYPES=${ALLOWED_MIME_TYPES}
RATE_LIMIT_PER_MINUTE=${RATE_LIMIT_PER_MINUTE}
EOF

chmod 600 "$OUT_FILE" || true

echo "✅ Wrote $OUT_FILE"
echo "Next: npm install && npx prisma generate && npm run dev"
